# Generated by Django 5.0.9 on 2024-10-11 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_image_total_likes_and_more'),
        ('recipe', '0006_report_category_report_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='recipe.report'),
        ),
    ]
