# Generated by Django 5.0.9 on 2024-10-28 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_contact'),
        ('recipe', '0008_recipebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='purchased_books',
            field=models.ManyToManyField(blank=True, to='recipe.recipebook'),
        ),
    ]
