# Generated by Django 5.0.9 on 2024-10-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_remove_rating_unique_report_user_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('BRK', 'Breakfast'), ('LCH', 'Lunch'), ('DIN', 'Dinner'), ('DES', 'Dessert'), ('APP', 'Appetizer')], default='DIN', max_length=3),
        ),
        migrations.AddField(
            model_name='report',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reports/'),
        ),
    ]
